### ISSUE TITLE
trees not dropping saplings in 1.17 version

### ISSUE THREAD

**Issue by EEEEE555** [DawnTeamMC/Promenade#19] opened 2021-07-12 19:06 UTC

**Comment by YanisBft** [comment] 2021-07-12 19:59
I can't reproduce this issue, can you give more information please? With the latest version, leaves have the same chance to drop saplings as the vanilla leaves

**Comment by Hugman76** [comment] 2021-07-25 10:28
This was fixed in the latest version.

**Closed by Hugman76** 2021-07-25 10:28 UTC
