### ISSUE TITLE
Server and client blocks are unsynced

### ISSUE THREAD

**Issue by NantaArthur123** [DawnTeamMC/Promenade#120] opened 2023-04-15 18:09 UTC
### What happened?

Promenade version: 3.2.0 for 1.19.4
Fabric Version: 0.14.18
How to recreate: Join a server that has promenade
Server Log: 
[latest (3).log](https://github.com/DawnTeamMC/Promenade/files/11240297/latest.3.log)
Client Log:
[latest.log](https://github.com/DawnTeamMC/Promenade/files/11240298/latest.log)

Edit: After I test in single player, no shuffle/bug happening, only when joining server.

Screenshot image
![2023-04-16_01 03 43](https://user-images.githubusercontent.com/109583020/232246158-3f769ffe-faa1-4eed-8387-6714792eb373.png)

### Dawn API version

4.2.0

### Fabric API version

0.14.18

**Comment by Hugman76** [comment] 2023-04-16 15:31
I can reproduce the issue. I have no idea of what's happening here yet...

**Comment by DieFetteBrxnette** [comment] 2023-04-16 19:29
It seems to be a problem with the dawn lib 4.2.0

**Comment by Hugman76** [comment] 2023-04-22 19:34
I'm so sorry I currently don't have any fixes available, I'm unable to track down where this is coming from at all.
It does seem to be related to the Dawn API somehow as Universal Ores seems to suffer from it too.

**Comment by Hugman76** [comment] 2023-05-06 10:07
This will be fixed with the Dawn API v4.2.1. Sorry about the huge delay on this issue.

**Closed by Hugman76** 2023-05-06 10:07 UTC
Labels: bug
